name: Build and Test Python
on:
  pull_request:
    paths:
      - payjoin-ffi/**
env:
  # Override the value from the rust-toolchain file
  # This is necessary because even though the correct toolchain
  # is explicitly specified for the rust-toolchain action,
  # rustup honors the rust-toolchain file over the default
  RUSTUP_TOOLCHAIN: 1.85

jobs:
  build-python-and-test:
    name: "Build and test python"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: payjoin-ffi/python
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install Rust 1.85.0"
        uses: dtolnay/rust-toolchain@1.85.0

      - name: "Install uv"
        uses: actions/setup-uv@v6
        with:
          version: "0.8.2"
          enable-cache: true

      - name: "Use cache"
        uses: Swatinem/rust-cache@v2

      - name: "uv sync"
        run: uv sync --all-extras

      - name: "Generate payjoin-ffi.py and binaries"
        run: bash ./scripts/generate_bindings.sh

      - name: "Build wheel"
        run: uv build --wheel

      - name: "Install wheel"
        run: uv run pip install ./dist/*.whl

      - name: "Run tests"
        run: uv run python -m unittest --verbose
